### ISSUE TITLE
helper.php error

### ISSUE THREAD

**Issue by IADDIC** [gazugafan/chirp#1]
hello @gazugafan 

I was trying out the app you have created as it seems to be well thought out, especially since you have taken into account the rate-limiting!  

I do have a problem though.  when I run php chirp I get this parse error:

Parse error: syntax error, unexpected '?' in /home/proje485/public_html/iaddicshelters.net/BOT/vendor/laravel-zero/foundation/src/Illuminate/Foundation/helpers.php on line 494

I have googled for a solution and it seemed it may be related to php version error.  However; I am using PHP Version 7.2.16
--

Any ideas what may be getting in the way.  I am not a programmer just trying my best to get some tools in place to help my efforts!  Thanks  Rich

**Comment by gazugafan** [comment]
Hmm... yeah the error is deep in the Laravel framework, and like you said, it sounds like it happens if you're not running PHP 7.x. I wonder if maybe you have PHP 7 installed, but you're not actually running it? If you do ```php -v``` does it list the right version?

**Comment by IADDIC** [comment]
O.K. that is very interesting .. php info in the directory and on the domain both show PHP 7.2.16.  So, I'll debug what is going on and then let you know where I am.  thanks for replying sooo quickly!

**Comment by IADDIC** [comment]
O.K. I have it figured out and all is well at the moment!  First I am on a shared host.  To overcome the fact that the server they have me on is default php version is php56 I need to call the version I want to use in the command.  for example:

[~/public_html/directory/subdirectory]# /usr/local/php72/bin/php-cli chirp

I do the same for the cron and I can use the application.  I'll see if the script runs on the schedule.  I have added a user and your script retrieved the followers.  

At this point, I'll close the topic and open a new one if anything else comes up.  I really do like how you have put this together.  Thanks for applying the fuzz and rate limiting logic.  With enough users to follow this could become a set it and forget it app.
