### ISSUE TITLE
Count = ? not working

### ISSUE THREAD

**Issue by IADDIC** [gazugafan/chirp#2]
Hello again @gazugafan ~ I have the script running and it is cycling through a list I set and all seems to be well except one point.  The script is not recognizing a change to the count variable.  I changed the value from 1 to 3 but every time the script runs it only increments the followers by 1 not 3 as expected.

`// Changed count from 1 to 3 -- RMG 3/28/2019 	 
	protected $signature = 'process:work
							{fuzz=0 : If specified, we\'ll wait up to this random number of seconds before each follow/unfollow }
							{count=3 : The number of follows/unfollows to attempt this time }';`

Also: are you familiar with a script that would move all muted contacts to a list.  As I am thinking through how this is working I would offer that the main follower is associated with a topic (why else follow their followers) so muting them is nice ( I like that feature) but adding them to a list would be stellar!  

I see I am the only user that has commented up to this point.  Are you interested in hearing a users perspective or was mainly intended to be a script you intended to use personally?  If you "need or want" ideas I have a few to offer.  If not, no worries...I love the throttling of the script which separates you from all others!  

Thanks,  Rich

**Comment by gazugafan** [comment]
Glad you got it working! I think you're modifying the signature of the command, which is basically just the help description that gets printed out. If you go to the end of that file and look at line 86, that's where the count and schedule are actually set. The "250" on that line is the fuzz, and the "1" is the count.

This was just a little weekend side-project that I thought other people might be able to make use of. I don't have much time to devote to it right now, but you're definitely welcome to make feature requests! I like the idea of adding people to a list when you add them to be followed.

**Comment by IADDIC** [comment]
all is well.  Thanks
