### ISSUE TITLE
Variables

### ISSUE THREAD

**Issue by IADDIC** [gazugafan/chirp#4]
He Ken:

Quick question if I may.  Reading through your documentation in the WorkCommand file I see where you indicate the schedule defaults to 5 minutes and a fuzzy of about 4.2 minutes.  You indicate that the schedule can be changed to lengthen or shorten the default 5 minutes and I see it here:  lines 86-92.

		$schedule->command(static::class, ['250', '1'])
			->withoutOverlapping()
			->appendOutputTo('chirp.log')
			**->everyFiveMinutes()**
			->weekdays()
			->timezone('US/Central')
			->between('10:00', '16:00')

So if I wanted to change the schedule to run once every 7 minutes, what would I for 		
			->everyFiveMinutes()

Do I enter 7 for 7 minutes or 7/5 or 1.4 minutes? id the variable really Every Five Minutes?

secondly, how do I specify Monday through Saturday?   

lastly, what is the withoutOverlapping()? 
			
Thanks much, Rich

**Comment by gazugafan** [comment]
Check out the documentation here for how to define the schedule...
https://laravel.com/docs/5.7/scheduling#defining-schedules

... you'll probably need to use the ```cron()``` method to have it run every seven minutes. You could probably specify the mon-sat there as well, like...
```->cron('*/7 * * * 1-6')```

The ```withoutOverlapping()``` method makes sure that one run of the task doesn't overlap with the next run. If you had it set to run every minute, for example, and for some reason it took more than 1 minute to run once, the next run would start running before the previous run had completed. ```withoutOverlapping()``` prevents this from happening by not allowing the next run to start if the previous one hasn't finished.
