### ISSUE TITLE
Question on timing

### ISSUE THREAD

**Issue by IADDIC** [gazugafan/chirp#5]
Hi Ken,  I was reviewing the chirp.log and notice that the pattern is very consistent.  

There is some ambiguity in the log in that it doesn't say the time when a twitter account was actually sent to Twitter so I need to ask: are the times in the chirp.log file the window in which the user is processed or the time stamp of the actual user being sent to Twitter?  

If it is the later then the time is not taking into account the fuzzy part of the equation because it is too regular of a pattern.

If it is the former, then a timestamp for when the user id is actually sent to twitter would be beneficial.

Also, if the times recorded are the window of processing then I take it the fuzzy logic is a subtraction number from 5 minutes, not a plus or minus amount from 5 minutes.  Here too the 5 minutes interval seems too regular for any addition to take place.

Am I understanding this right?

Thanks, Rich 

2019-04-04 11:29:12 UTC: Starting work...
Followed AquQQQQQQsGirl06!
There aren't any users to unfollow
2019-04-04 11:29:12 UTC: Finished work!
2019-04-04 11:34:12 UTC: Starting work...
Followed JQQQQQQ7!
There aren't any users to unfollow
2019-04-04 11:34:12 UTC: Finished work!
2019-04-04 11:39:11 UTC: Starting work...
Followed wQQQQQQQr!
There aren't any users to unfollow
2019-04-04 11:39:12 UTC: Finished work!
2019-04-04 11:44:11 UTC: Starting work...
Followed cQQQQQQQQcarr!
There aren't any users to unfollow
2019-04-04 11:44:12 UTC: Finished work!
2019-04-04 11:49:11 UTC: Starting work...
Followed allisQQQQorres!
There aren't any users to unfollow
2019-04-04 11:49:11 UTC: Finished work!
2019-04-04 11:54:11 UTC: Starting work...
Followed da2QQQQQQ861!
There aren't any users to unfollow
2019-04-04 11:54:12 UTC: Finished work!
2019-04-04 11:59:11 UTC: Starting work...
Followed nQQQQQQQQQQQQdru!
There aren't any users to unfollow
2019-04-04 11:59:11 UTC: Finished work!
2019-04-04 12:04:12 UTC: Starting work...
Followed JoQQQQQQQQQel7!
There aren't any users to unfollow
2019-04-04 12:04:12 UTC: Finished work!
2019-04-04 12:09:11 UTC: Starting work...
Followed SQQasi!
There aren't any users to unfollow
2019-04-04 12:09:11 UTC: Finished work!

**Comment by gazugafan** [comment]
I think this is a bug, actually. The timestamp is listed AFTER waiting the fuzzy number of seconds, so it shouldn't be consistent like this. I'm noticing the same thing on my end as well. I'll try to get a fix out today.

**Comment by gazugafan** [comment]
Oh geeze, yeah I see the problem. I just pushed a fix. You might not be able to pull the change very easily, since it modifies the WorkCommand.php file (which you may have also modified yourself). It's just a one line change, though. Line 36 in that file...
https://github.com/gazugafan/chirp/commit/6942048c2fe5f1ec268c1f30f1c7015d80667af3

**Comment by IADDIC** [comment]
Hey Ken,  thanks...I'll just change line 36 and be done with it.  Easy enough and thank you for turning around a fix.  Have a good Friday and weekend!  Rich:



​



​

   
    
Richard Grabowski
    
M: 1-214-243-6518
E: me@richardgrabowski.us    

    
 
       
    


    


UN ECOSOC – Consultative Status

🏠
